{
    'time': 10,
    'submited': False,
    'target_func': 'opacus_split_review',
    'model_name': 'FF-split',
    'dataset_name': 'Home_and_Kitchen',
    'label_type': 'sentiment',
    'select_num': 1,
    'early_stopping': False,
    'device': 0,
    'LR': 1e-3,
    'EPSILON': 5.0,
    'EPOCH_SET_EPSILON': False,
    'DELTA': 1e-5,
    'MAX_GRAD_NORM': 1.2,
    'BATCH_SIZE': 128,
    'MAX_PHYSICAL_BATCH_SIZE': 128/4,
    'EPOCHS': 2,
    'train_configs': {
        'hidden_size': [150, 110],
        'embedding_size': 100,
        'sequence_length': 50,
    },
    'dispatcher_ip': dispatcher_ip,
    'dispatcher_port': dispatcher_port,
}
{
    'time': 5,
    'submited': False,
    'target_func': 'opacus_split_review',
    'model_name': 'LSTM-split',
    'dataset_name': 'Home_and_Kitchen',
    'label_type': 'sentiment',
    'select_num': 1,
    'early_stopping': False,
    'device': 0,
    'LR': 1e-3,
    'EPSILON': 5.0,
    'EPOCH_SET_EPSILON': False,
    'DELTA': 1e-5,
    'MAX_GRAD_NORM': 1.2,
    'BATCH_SIZE': 128,
    'MAX_PHYSICAL_BATCH_SIZE': 128/4,
    'EPOCHS': 2,
    'train_configs': {
        'n_layer': 2,
        'hidden_size': 40,
        'embedding_size': 100,
        'sequence_length': 50,
    },
    'dispatcher_ip': dispatcher_ip,
    'dispatcher_port': dispatcher_port,
} 